

gnu : 
	g++ -Werror -Wall -Wextra -Wconversion -std=c++11 -pedantic -O -o gnu driver.cpp PRNG.cpp

noflags :
	g++ -std=c++11 -o gnu driver.cpp PRNG.cpp
  
32 :
	g++ -std=c++11 -o gnu driver.cpp PRNG.cpp -m32