
sudoku : Sudoku.cpp driver.cpp
	g++ -o sudoku driver.cpp Sudoku.cpp -O2 -Wall -Wextra -std=c++11 -pedantic -Wconversion -Werror -g
	
noflags : Sudoku.cpp driver.cpp
	g++ -o sudoku driver.cpp Sudoku.cpp -O2 -std=c++11 -g
	
32 : Sudoku.cpp driver.cpp
	g++ -o sudoku driver.cpp Sudoku.cpp -O2 -std=c++11 -g

clean :
	rm ./sudoku

