
default : 
	g++ -o gnu driver-sample.cpp ObjectAllocator.cpp PRNG.cpp -O -Wextra -Wall -std=c++11 -pedantic -Wconversion 


int :	
	g++ -o gnu driver-sample-ints.cpp BSTree.cpp AVLTree.cpp ObjectAllocator.cpp PRNG.cpp -O -Wextra -Wall -std=c++11 -pedantic -Wconversion 

clean :
	rm ./gnu