spvector.c File Reference
spvector.c File Reference
Implementation of functions protoyped in spvector.h. Also includes definitions of Element Node and Row Node, which are hidden from interface file.
#include <stdlib.h>
#include <stdio.h>
#include "spvector.h"
Classes
struct ElementNode
struct RowNode
Typedefs
typedef struct ElementNode ElementNode
typedef struct RowNode RowNode
Functions
void printf_elements (ConstElementNode_handle p_e, char *fmt, int dim)
void print_elements (ConstElementNode_handle p_e)
void print_rows (ConstRowNode_handle p_r)
void printf_rows (ConstRowNode_handle p_r, char *fmt, int dim)
int determinant (ConstRowNode_handle p_r, int dim)
Detailed Description
Implementation of functions protoyped in spvector.h. Also includes definitions of Element Node and Row Node, which are hidden from interface file.
Author
Haven Breithaupt
DP email: h.breithaupt@digipen.edu
Course: CS225
Assignment 1
Date
5/23/15
Function list: Vector Functions
printf_elements : prints out a sparse vector (of specified dimension)
print_elements : prints out a sparse vector
print_rows : prints out a sparse matrix
printf_rows : prints out a sparse matrix (of specified dimension)
determinant : finds determinant of sparse matrix (not implemented)
make_node : makes an element node
insert_element : inserts an element node into sparse vector
delete_element : deletes node form sparse vector
get : gets data from node at specified pos (if exists)
scalar_product : finds scalar product between two vectors
add : adds two vectors, returns a new vector
Matrix Functions:
make_row : makes a RowNode
ZeroRowRemover : removes any zero'd out rows in a matrix (deletes all in one call)
insert_row : inserts a row into a matrix
insert_element2 : inserts an element node at specified row and column
find_row : retrieves a pointer to specified row
transpose : transposes a matrix, returns new matrix
mult : multiplies two matrices
free_rows : deallocates matrix
Definition in file spvector.c.
Typedef Documentation
typedef struct ElementNode ElementNode
Definition at line 85 of file spvector.c.
typedef struct RowNode RowNode
Definition at line 86 of file spvector.c.
Function Documentation
int determinant (ConstRowNode_handle p_r, int dim)
Finds determinant of matrix (NOT IMPLEMENTED).
Parameters
p_r Matrix to use.
dim Dimension of matrix (used for rows and columns).
Returns
Determinant of the matrix.
Definition at line 210 of file spvector.c.
Referenced by test24().
void print_elements (ConstElementNode_handle p_e)
Prints all elements in a vector, no zero.
Parameters
p_e Pointer to vector to print out.
Definition at line 129 of file spvector.c.
Referenced by print_rows(), test0(), test1(), test10(), test12(), test2(), test3(), test4(), test5(), and test9().
void print_rows (ConstRowNode_handle p_r)
Prints out all non-zero elements in list of rows (matrix).
Parameters
p_r Matrix to print out.
Definition at line 147 of file spvector.c.
References print_elements().
Referenced by test16(), test17(), test18(), test19(), test20(), test21(), and test22().
void printf_elements (ConstElementNode_handle p_e, char * fmt, int dim)
Prints out a vector, inserts 0 for non-existent positions, assumes dim = length of vector, does not check for more values after dim.
Parameters
p_e Pointer to the vector to print out.
fmt Format to print out each number.
dim Dimension of vecor (assumedly as passed from caller).
Definition at line 107 of file spvector.c.
Referenced by printf_rows(), test0(), test1(), test10(), test11(), test13(), test14(), test15(), test2(), test3(), test4(), test5(), test6(), and test8().
void printf_rows (ConstRowNode_handle p_r, char * fmt, int dim)
Prints out matrix, inserts 0 at non-existent positions. Assumes the number of rows and columns is dim, will not check for data after dim.
Parameters
p_r Matrix to print out.
fmt Format to print out each element.
dim Dimension of matrix (used for rows and columns).
Definition at line 175 of file spvector.c.
References printf_elements().
Referenced by test13(), test14(), test15(), test16(), test17(), test18(), test19(), test20(), test21(), test23(), and test24().