spvector.h File Reference
spvector.h File Reference
Interface file for use of sparse vector and sparse matrix functions.
#include <stdio.h>
Typedefs
typedef struct ElementNode * ElementNode_handle
typedef struct ElementNode const * ConstElementNode_handle
typedef struct RowNode * RowNode_handle
typedef struct RowNode const * ConstRowNode_handle
Functions
void printf_elements (ConstElementNode_handle p_el, char *fmt, int dim)
void print_elements (ConstElementNode_handle p_el)
int insert_element (ElementNode_handle *p_e, int pos, int val)
void delete_element (ElementNode_handle *p_e, int pos)
int get (ConstElementNode_handle p_e, int pos)
int scalar_product (ConstElementNode_handle p_e1, ConstElementNode_handle p_e2)
ElementNode_handle add (ConstElementNode_handle p_e1, ConstElementNode_handle p_e2)
void printf_rows (ConstRowNode_handle p_r, char *fmt, int dim)
void print_rows (ConstRowNode_handle p_r)
int insert_row (RowNode_handle *p_r, int pos, ElementNode_handle p_e)
int insert_element2 (RowNode_handle *pp_r, int pos_row, int pos_col, int val)
RowNode_handle find_row (RowNode_handle *pp_r, int pos)
RowNode_handle transpose (ConstRowNode_handle p_r)
RowNode_handle mult (ConstRowNode_handle p_r1, ConstRowNode_handle p_r2)
void free_rows (RowNode_handle p_r)
int determinant (ConstRowNode_handle p_r, int dim)
Detailed Description
Interface file for use of sparse vector and sparse matrix functions.
Author
Haven Breithaupt
DP email: h.breithaupt@digipen.edu
Course: CS225
Assignment 1
Date
5/23/15
Definition in file spvector.h.
Typedef Documentation
typedef struct ElementNode const* ConstElementNode_handle
Definition at line 39 of file spvector.h.
typedef struct RowNode const* ConstRowNode_handle
Definition at line 41 of file spvector.h.
typedef struct ElementNode* ElementNode_handle
Definition at line 38 of file spvector.h.
typedef struct RowNode* RowNode_handle
Definition at line 40 of file spvector.h.
Function Documentation
ElementNode_handle add (ConstElementNode_handle p_e1, ConstElementNode_handle p_e2)
Referenced by test10(), test8(), and test9().
void delete_element (ElementNode_handle * p_e, int pos)
Referenced by test3(), test4(), and test5().
int determinant (ConstRowNode_handle p_r, int dim)
Finds determinant of matrix (NOT IMPLEMENTED).
Parameters
p_r Matrix to use.
dim Dimension of matrix (used for rows and columns).
Returns
Determinant of the matrix.
Definition at line 210 of file spvector.c.
Referenced by test24().
RowNode_handle find_row (RowNode_handle * pp_r, int pos)
void free_rows (RowNode_handle p_r)
Referenced by test13(), test14(), test15(), test16(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), and test24().
int get (ConstElementNode_handle p_e, int pos)
int insert_element (ElementNode_handle * p_e, int pos, int val)
Referenced by test0(), test1(), test10(), test11(), test12(), test13(), test14(), test15(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
int insert_element2 (RowNode_handle * pp_r, int pos_row, int pos_col, int val)
Referenced by test16(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), and test24().
int insert_row (RowNode_handle * p_r, int pos, ElementNode_handle p_e)
Referenced by test13(), test14(), and test15().
RowNode_handle mult (ConstRowNode_handle p_r1, ConstRowNode_handle p_r2)
Referenced by test23().
void print_elements (ConstElementNode_handle p_e)
Prints all elements in a vector, no zero.
Parameters
p_e Pointer to vector to print out.
Definition at line 129 of file spvector.c.
Referenced by print_rows(), test0(), test1(), test10(), test12(), test2(), test3(), test4(), test5(), and test9().
void print_rows (ConstRowNode_handle p_r)
Prints out all non-zero elements in list of rows (matrix).
Parameters
p_r Matrix to print out.
Definition at line 147 of file spvector.c.
References print_elements().
Referenced by test16(), test17(), test18(), test19(), test20(), test21(), and test22().
void printf_elements (ConstElementNode_handle p_e, char * fmt, int dim)
Prints out a vector, inserts 0 for non-existent positions, assumes dim = length of vector, does not check for more values after dim.
Parameters
p_e Pointer to the vector to print out.
fmt Format to print out each number.
dim Dimension of vecor (assumedly as passed from caller).
Definition at line 107 of file spvector.c.
Referenced by printf_rows(), test0(), test1(), test10(), test11(), test13(), test14(), test15(), test2(), test3(), test4(), test5(), test6(), and test8().
void printf_rows (ConstRowNode_handle p_r, char * fmt, int dim)
Prints out matrix, inserts 0 at non-existent positions. Assumes the number of rows and columns is dim, will not check for data after dim.
Parameters
p_r Matrix to print out.
fmt Format to print out each element.
dim Dimension of matrix (used for rows and columns).
Definition at line 175 of file spvector.c.
References printf_elements().
Referenced by test13(), test14(), test15(), test16(), test17(), test18(), test19(), test20(), test21(), test23(), and test24().
int scalar_product (ConstElementNode_handle p_e1, ConstElementNode_handle p_e2)
Referenced by test6(), and test7().
RowNode_handle transpose (ConstRowNode_handle p_r)
Referenced by test22(), and test23().